### ISSUE TITLE
problem with getRenditions

### ISSUE THREAD

**Issue by havishmanakkina** [epiclabs-io/ngx-epic-video-player-demo#1] opened 2019-01-22 07:17 UTC
we are using your player in an ionic project 
it is working fine when we serve on the web browser
but when we build and run it in ios/android device
while using getRenditions 
we are getting an error
<img width="686" alt="screen shot 2019-01-22 at 12 46 06 pm" src="https://user-images.githubusercontent.com/28451627/51518436-de232c80-1e43-11e9-8771-82ab099e89ce.png">

**Comment by adripanico** [comment] 2019-01-22 07:27
Hummm. I'll review the code but is going to be difficult to check it out in your scenario.

**Comment by adripanico** [comment] 2019-01-22 07:41
Could you share the video URL that is causing the issue?

**Comment by adripanico** [comment] 2019-01-22 07:47
Where exactly are you calling to getRenditions()? Have you try to call this method, for instance, on the canplay event?

**Comment by havishmanakkina** [comment] 2019-01-22 08:01
Thank you for responding..
we are calling getRenditions() in canplay event itself.
and we are getting the same issue as above
url that we are using is https://s3.amazonaws.com/demovideo-on-demand-destination-lh3quivctpyv/4ffa83d6-65eb-41f6-a36f-9fe25cfacf23/hls/videoplayback.m3u8'
we are using the events excatly as in your demo
<img width="565" alt="screen shot 2019-01-22 at 1 31 14 pm" src="https://user-images.githubusercontent.com/28451627/51520563-0877e880-1e4a-11e9-9cee-bfb0f8a28741.png">

**Comment by adripanico** [comment] 2019-01-22 11:39
Ok, the problem is that the browser you are using does not support MediaSourceExtension. I will publish a new version that will avoid to rise the error when calling to getRenditions(), but you will still not be able to list them nor choose one.

**Comment by havishmanakkina** [comment] 2019-01-22 11:57
even in the new version will we not be able to use getRenditions() ?? 
isnt there any fix for that so that we can use getRenditions()?

**Comment by adripanico** [comment] 2019-01-22 13:33
Again, this is based on MediaSourceExtension. If the browser does not provide it, currently there is not a way to retrieve nor set a rendition.

This is not a problem with this library, as you can see in the [Hls.js documentation](https://video-dev.github.io/hls.js/latest/#compatibility).

**Comment by adripanico** [comment] 2019-01-23 11:36
Closed by commit 49a6d7a and release [1.0.3](https://www.npmjs.com/package/ngx-epic-video-player/v/1.0.3).

**Closed as completed by adripanico** 2019-01-23 11:36 UTC
Labels: bug
